add crwals
gsainfoteam/ziggle-be pull request #17
Opened 2024-02-06 13:46 UTC by siwonpada

2024-02-07 05:09 UTC, 2paperstar commented on src/notice/notice.service.ts
> +        additionalContent: [],
여기 빈배열 맞아요?

2024-02-07 12:29 UTC, siwonpada commented on src/notice/notice.service.ts
> +        additionalContent: [],
이거 get list를 사용할 때는 여러 공지를 한번에 볼때이고, additionalContent는 공지를 클릭한 다음에 공지 하나를 받아올 때만 받아온 다고 생각을 해서 일단을 이렇게 적기는 함, 프엔에 따라서 바뀌어야 할 지도?

2024-02-07 13:37 UTC, 2paperstar requested changes

2024-02-07 13:37 UTC, 2paperstar commented on src/notice/notice.service.ts
> +      });
```suggestion
    const $ = from(reactions)
      .pipe(
        groupBy(({ emoji }) => emoji),
        mergeMap((group) => group.pipe(toArray())),
        toArray(),
      );
      const result = await firstValueFrom($);
```

2024-02-07 13:37 UTC, 2paperstar commented on src/notice/notice.service.ts
> +      });
문법 안 맞을 수도 있음

2024-02-07 16:39 UTC, 2paperstar requested changes

2024-02-07 16:39 UTC, 2paperstar commented on src/notice/notice.service.ts
> +              }),
지금 봤는데 이렇게 되면 영어 공지가 안 넘어올 것 같아요

2024-02-07 16:39 UTC, 2paperstar commented on src/notice/notice.service.ts
> +                selectors: [{ selector: 'a', options: { ignoreHref: true } }],
1000자까지 끊어서 넘기기?

2024-02-07 16:39 UTC, 2paperstar commented on src/notice/notice.service.ts
> +      }): GeneralNotice => ({
공지 목록에서도 좋아요(🔥) 개수랑 내가 눌렀는지를 알아야 해요

2024-02-07 16:39 UTC, 2paperstar commented on src/notice/notice.service.ts
> +        isReacted: reactions.map(({ userId }) => userId).includes(userUuid),
```suggestion
        isReacted: reactions.some(({ userId }) => userId === userUuid),
```

2024-02-07 16:39 UTC, 2paperstar commented on src/notice/notice.service.ts
> +        notice.reminders.filter(({ uuid }) => uuid === userUuid).length > 0,
```suggestion
        notice.reminders.some(({ uuid }) => uuid === userUuid),
```

2024-02-07 16:39 UTC, 2paperstar commented on src/notice/notice.service.ts
> +        notice.reminders.filter(({ uuid }) => uuid === userUuid).length > 0,
빈 배열에 some 쓰면 false라서 괜찮음

2024-02-09 03:47 UTC, 2paperstar requested changes

2024-02-09 03:47 UTC, 2paperstar commented on src/notice/notice.service.ts
> +      }),
요기 리마인더 여부까지 넣어주세요..!

2024-02-11 12:48 UTC, siwonpada commented on src/notice/notice.service.ts
> +              }),
cralw한 것 중에서 영어공지가 없어서(학사 공지에 영어공지가 없어서)일단 한국어로 한 것입니다.

2024-02-11 12:49 UTC, siwonpada commented on src/notice/notice.service.ts
> +                selectors: [{ selector: 'a', options: { ignoreHref: true } }],
무슨 소리인지 잘 모르겠어요

2024-02-11 12:49 UTC, 2paperstar commented on src/notice/notice.service.ts
> +              }),
위에는 그게 맞는 것 같은데 밑에는 일반 공지들이어서요

2024-02-11 13:12 UTC, 2paperstar commented on src/notice/notice.service.ts
> +                selectors: [{ selector: 'a', options: { ignoreHref: true } }],
slice(0, 1000)

2024-02-11 14:23 UTC, 2paperstar approved these changes
LGTM

crawls 배열에서 제일 마지막거 리턴 해주는 것만 하면 될 것 같아요

그리고 지금 학사 공지들 마이그레이션 코드를 작성하던지 나중에 프로덕션 올리기 전에 crawl 테이블로 옮기는 작업이 필요할 것 같습니다!!

2024-02-12 00:31 UTC, 2paperstar approved these changes

2024-02-12 00:32 UTC, 2paperstar requested changes

2024-02-12 00:32 UTC, 2paperstar commented on src/notice/notice.service.ts
> +  ): Promise<ExpandedGeneralNotice> {
얘도 lang을 받아야 영어공지를 볼 수 있겠네요ㅜㅜ

2024-02-12 09:23 UTC, 2paperstar approved these changes
굿굿!!!! 수고하셨어용

2024-02-13 14:26 UTC, merged