migrate prisma
gsainfoteam/ziggle-be pull request #2
Opened 2023-09-25 14:55 UTC by siwonpada

확인 필요, 테스트 필요

2023-09-25 14:56 UTC, 2paperstar commented
당신 미치셨습니까

2023-09-25 14:57 UTC, siwonpada commented
???

2023년 9월 25일 (월) 오후 11:56, Lee Boseong ***@***.***>님이 작성:

> 당신 미치셨습니까
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gsainfoteam/ziggle-be/pull/2#issuecomment-1733889704>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATTQFSHUFX6LSZSGM6CVLKLX4GLR5ANCNFSM6AAAAAA5GHL4PM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-25 14:58 UTC, 2paperstar requested changes
아직 다 안 봄 (사실 하나도 안 봄)

2023-09-25 14:58 UTC, 2paperstar commented on src/prisma/prisma.service.ts
> +          url: process.env.DATABASE_URL,
configService 사용하기

2023-09-26 00:02 UTC, 2paperstar commented
도커파일 같아 바꿔줘야하는거 아닌가요?

2023-09-26 00:06 UTC, 2paperstar commented
브랜치 병합 되는거랑 DB마이그레이션 되는거를 어느 순간에 어떻게 처리해야할지 논의가 필요할 것 같아요

2023-11-15 12:39 UTC, 2paperstar approved these changes

2023-11-15 13:11 UTC, merged