use strict option and postgresql database
gsainfoteam/ziggle-be pull request #23
Opened 2024-03-18 16:39 UTC by siwonpada

strict option을 사용하여 type확인을 더 강화하였으며, code의 구조개선이 조금 있었습니다.
또한 현재 MSA를 사용하기 위해서 관련되 code는 모두 제거하였으니 확인 부탁드립니다.

2024-03-19 00:39 UTC, 2paperstar commented on src/user/guard/id.guard.ts
이 파일 이름 오타인가요?

2024-03-19 01:00 UTC, 2paperstar requested changes
대부분 훑은 것 같습니당

ConfigModule을 감싼 모듈을 하나 더 만들어서 (ZiggleConfigModule? ApiConfigModule?) 해당 모듈 안에서 validation과 typing된 변수 값들을 내보내는게 개인적으로는 경험이 좋았는데, 이 방식은 어떤가요?

2024-03-19 01:00 UTC, 2paperstar commented on src/user/guard/id.guard.ts
이 파일 이름 오타인가요?

2024-03-19 01:00 UTC, 2paperstar commented on src/user/dto/req/logout.dto.ts
> +  access_token: string;
얘 JWT 아닐걸요..?

2024-03-19 01:00 UTC, 2paperstar commented on src/user/dto/res/userInfoRes.dto.ts
IdP 새로운 버전 들어오면 필드 이름 바꾸는거 나중에 고려

2024-03-19 01:00 UTC, 2paperstar commented on src/user/user.service.ts
> +      throw new UnauthorizedException();
400이 낫지 않을까..?

2024-03-19 01:00 UTC, 2paperstar commented on src/tag/tag.controller.ts
>      }
name이 있으면 -> findTag
search가 있으면 -> searchTags
아무것도 없으면 -> findAllTags

흐름이면 안 되나요? early return이 되기도 해서 깔끔할 것 같은데

2024-03-19 01:00 UTC, 2paperstar commented on src/tag/tag.service.ts
여기도 그렇고 유저 서비스도 그렇고 await 없이 then으로 묶은건 의도한건가요?

2024-03-19 01:00 UTC, 2paperstar commented on src/notice/notice.mapper.ts
> +  async NoticeFullContentToGeneralNoticeList(
이 함수는 ExpandGeneral 함수의 결과를 조작하는 방식으로 간단하게 처리 가능하지 않을까요?

2024-03-19 01:00 UTC, 2paperstar commented on src/notice/notice.service.ts
>      await this.noticeRepository.addAdditionalNotice(
권한 validation

2024-03-19 01:00 UTC, 2paperstar commented on src/notice/notice.service.ts
>      await this.noticeRepository.addForeignContent(
권한 validation

2024-03-19 01:00 UTC, 2paperstar commented on src/notice/notice.service.ts
>      this.imageService.deleteImages(notice.files.map(({ url }) => url));
documents도 지우기?

2024-03-19 03:56 UTC, siwonpada commented on src/notice/notice.service.ts
>      this.imageService.deleteImages(notice.files.map(({ url }) => url));
충격적이게도 이 방법으로 document도 지워지기는 함

2024-03-19 04:48 UTC, siwonpada commented on src/notice/notice.mapper.ts
> +  async NoticeFullContentToGeneralNoticeList(
타입을 확실히 명시하고 싶어서 따로 만든 것이기는 한데, 위의 함수를 조작하면서, 타입도 확실히 다르게 줄 수 있는 방법이 있을 까요?

2024-03-19 04:51 UTC, 2paperstar commented on src/notice/notice.service.ts
>      this.imageService.deleteImages(notice.files.map(({ url }) => url));
헉 그렇겠네
그러면 그냥 fileService? 가져오는게 낫지 않나 싶기도 하고

애초에 imageService에서는 image인지 validation하고 documentService에서는 document인지 validation하는게 안전할 것 같음

2024-03-19 04:52 UTC, 2paperstar commented on src/notice/notice.mapper.ts
> +  async NoticeFullContentToGeneralNoticeList(
const expanded = await this.~~();
return {
  ...expanded,
  // ...
}

이런 방식이면 되지 않을까요?

2024-03-19 05:02 UTC, siwonpada commented on src/user/dto/res/userInfoRes.dto.ts
확인

2024-03-19 05:24 UTC, siwonpada commented on src/notice/notice.mapper.ts
> +  async NoticeFullContentToGeneralNoticeList(
확인

2024-03-20 10:52 UTC, 2paperstar requested changes

2024-03-20 10:52 UTC, 2paperstar commented on src/file/file.service.ts
> +    Promise.all(keys.map((key) => this.deleteFile(key)));
await이 안 돼요

2024-03-20 10:53 UTC, 2paperstar commented on src/notice/notice.mapper.ts
> +    const { content, additionalContents, ...result } =
```suggestion
    const { content, additionalContents: _, ...result } =
```

2024-03-20 11:02 UTC, 2paperstar approved these changes
![image](https://github.com/gsainfoteam/ziggle-be/assets/125528915/e3cd3bd7-f731-4170-9c30-364db6355c14)

2024-03-20 11:08 UTC, merged