feat: create or update fcm token
gsainfoteam/ziggle-be pull request #47
Opened 2024-05-16 15:26 UTC by GanghyeonSeo

fcm token을 create하거나 update하는 기능을 추가했습니다.

2024-05-16 16:49 UTC, siwonpada requested changes

2024-05-16 16:49 UTC, siwonpada commented on src/user/user.controller.ts
> +  async setFcmToken(@GetUser() user: User, @Body() fcmToken: setFcmTokenReq) {
여기 Guard안 붙어있는데, @GetUser가 작동하나요?

2024-05-17 04:54 UTC, GanghyeonSeo commented on src/user/user.controller.ts
> +  async setFcmToken(@GetUser() user: User, @Body() fcmToken: setFcmTokenReq) {
idpOptional Guard 붙여서 다시 올렸습니다.

2024-05-19 05:01 UTC, siwonpada approved these changes

2024-05-19 08:06 UTC, merged